import { Rubik } from "next/font/google";
import "./globals.css";
import { PostHogProvider } from "./providers";

const rubik = Rubik({
  subsets: ["latin"],
  weights: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className}`}>
        <PostHogProvider>{children}</PostHogProvider>
      </body>
    </html>
  );
}
